### ISSUE TITLE
Lisp error: (json-unknown-keyword "from")

### ISSUE THREAD

**Issue by asok** [Mon-Ouie/ruby-dev.el#1]
Hey I wanted to play with it but I got an error. 
This is from clean emacs 24.2 setup on OSX. 

I do this: `M-x toggle-debug-on-error RET`
And later `C-c C-b` in the ruby buffer with some content. And I am presented with this ugly thing:

``` elisp
Debugger entered--Lisp error: (json-unknown-keyword "from")
  signal(json-unknown-keyword ("from"))
  #[(char) "\302`f\211\206\n\303)\"\204\304\305\212\306v\210\307\310!)C\"\210\311\211u)\207" [char n char-equal :json-eof signal json-unknown-keyword -1 thing-at-point word nil] 5](97)
  mapc(#[(char) "\302`f\211\206\n\303)\"\204\304\305\212\306v\210\307\310!)C\"\210\311\211u)\207" [char n char-equal :json-eof signal json-unknown-keyword -1 thing-at-point word nil] 5] "false")
  json-read-keyword("false")
  apply(json-read-keyword "false")
  json-read()
  (condition-case ex (json-read) ((quote json-readtable-error) (message "ruby-dev failed to parse line: %s" line) nil))
  (progn (save-excursion (insert line)) (condition-case ex (json-read) ((quote json-readtable-error) (message "ruby-dev failed to parse line: %s" line) nil)))
  (unwind-protect (progn (save-excursion (insert line)) (condition-case ex (json-read) ((quote json-readtable-error) (message "ruby-dev failed to parse line: %s" line) nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (save-excursion (insert line)) (condition-case ex (json-read) ((quote json-readtable-error) (message "ruby-dev failed to parse line: %s" line) nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (with-current-buffer temp-buffer (unwind-protect (progn (save-excursion (insert line)) (condition-case ex (json-read) ((quote json-readtable-error) (message "ruby-dev failed to parse line: %s" line) nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (with-current-buffer temp-buffer (unwind-protect (progn (save-excursion (insert line)) (condition-case ex (json-read) ((quote json-readtable-error) (message "ruby-dev failed to parse line: %s" line) nil))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  (with-temp-buffer (save-excursion (insert line)) (condition-case ex (json-read) ((quote json-readtable-error) (message "ruby-dev failed to parse line: %s" line) nil)))
  (let ((response (with-temp-buffer (save-excursion (insert line)) (condition-case ex (json-read) ((quote json-readtable-error) (message "ruby-dev failed to parse line: %s" line) nil))))) (when response (let ((handler (ruby-dev-match-special-handler response))) (if handler (funcall (cdr handler) response) (setq ruby-dev-response-queue (append ruby-dev-response-queue (list response)))))))
  ruby-dev-enqueue-response("   from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:1056:in `gem'\n")
  (unwind-protect (ruby-dev-enqueue-response cur) (setq ruby-dev-received-output rest))
  (let ((cur (subseq ruby-dev-received-output 0 (1+ eol))) (rest (subseq ruby-dev-received-output (1+ eol)))) (unwind-protect (ruby-dev-enqueue-response cur) (setq ruby-dev-received-output rest)))
  (while (progn (setq eol (position 10 ruby-dev-received-output)) eol) (let ((cur (subseq ruby-dev-received-output 0 (1+ eol))) (rest (subseq ruby-dev-received-output (1+ eol)))) (unwind-protect (ruby-dev-enqueue-response cur) (setq ruby-dev-received-output rest))))
  (let* ((eol nil)) (while (progn (setq eol (position 10 ruby-dev-received-output)) eol) (let ((cur (subseq ruby-dev-received-output 0 (1+ eol))) (rest (subseq ruby-dev-received-output (1+ eol)))) (unwind-protect (ruby-dev-enqueue-response cur) (setq ruby-dev-received-output rest)))) nil)
  (catch (quote --cl-block-nil--) (let* ((eol nil)) (while (progn (setq eol (position 10 ruby-dev-received-output)) eol) (let ((cur (subseq ruby-dev-received-output 0 (1+ eol))) (rest (subseq ruby-dev-received-output (1+ eol)))) (unwind-protect (ruby-dev-enqueue-response cur) (setq ruby-dev-received-output rest)))) nil))
  (cl-block-wrapper (catch (quote --cl-block-nil--) (let* ((eol nil)) (while (progn (setq eol (position 10 ruby-dev-received-output)) eol) (let ((cur (subseq ruby-dev-received-output 0 ...)) (rest (subseq ruby-dev-received-output ...))) (unwind-protect (ruby-dev-enqueue-response cur) (setq ruby-dev-received-output rest)))) nil)))
  (block nil (let* ((eol nil)) (while (progn (setq eol (position 10 ruby-dev-received-output)) eol) (let ((cur (subseq ruby-dev-received-output 0 (1+ eol))) (rest (subseq ruby-dev-received-output (1+ eol)))) (unwind-protect (ruby-dev-enqueue-response cur) (setq ruby-dev-received-output rest)))) nil))
  (loop for eol = (position 10 ruby-dev-received-output) while eol do (let ((cur (subseq ruby-dev-received-output 0 (1+ eol))) (rest (subseq ruby-dev-received-output (1+ eol)))) (unwind-protect (ruby-dev-enqueue-response cur) (setq ruby-dev-received-output rest))))
  ruby-dev-process-filter(#<process ruby-dev> "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:777:in `report_activate_error': Could not find RubyGem pry (~> 0.9) (Gem::LoadError)\n   from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:211:in `activate'\n    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems.rb:1056:in `gem'\n    from /Users/asok/projects/ruby-dev.el/ruby-dev.rb:5\n")
  accept-process-output(#<process ruby-dev>)
  (while (not ruby-dev-response-queue) (accept-process-output ruby-dev-process))
  (catch (quote --cl-block-nil--) (while (not ruby-dev-response-queue) (accept-process-output ruby-dev-process)) nil)
  (cl-block-wrapper (catch (quote --cl-block-nil--) (while (not ruby-dev-response-queue) (accept-process-output ruby-dev-process)) nil))
  (block nil (while (not ruby-dev-response-queue) (accept-process-output ruby-dev-process)) nil)
  (loop until ruby-dev-response-queue do (accept-process-output ruby-dev-process))
  ruby-dev-read-response()
  (let ((response (ruby-dev-read-response))) (with-ruby-dev-data (success result) response (if (eql success :json-false) (ruby-dev-show-error response) (message "%s" result))))
  ruby-dev-eval-string(#("puts 'Hello World'" 0 5 (fontified t) 5 18 (fontified t face font-lock-string-face)) "/Users/asok/projects/KantoxWeb/test.rb" 1)
  ruby-dev-eval-buffer()
  call-interactively(ruby-dev-eval-buffer nil nil)
```

`M-x async-shell-command RET gem list | grep 'yard\|pry' RET` gives me this:

```
pry (0.9.10)
yard (0.8.3)
```

Any hints?

**Comment by Mon-Ouie** [comment]
Hey,

It seems the Ruby process is raising an exception. Since the backtrace mentions rubygems, I'd think it's related to a `require'. What happens if you run the ruby-dev.rb script manually?

It might be that the ruby environment ruby-dev.el is starting doesn't work entirely (not the same ruby version, or rubygems not being set up using the same directiories).

**Comment by asok** [comment]
Yes, thanks it was problem with my rvm setup.
